version: '3.9'

services:
  app:
    build: .
    volumes:
      - .:/slcm
    ports:
      - 8000:8000

    image: app:slcm
    container_name: api_slcm
    command: python manage.py runserver 0.0.0.0:8000
    environment: 
      - DB_NAME=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    depends_on:
      - db

  db:
    image: postgres
    container_name: db_slcm
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydatabase
    ports:
      - 5432:5432
    volumes:
      - slcm_db_data:/var/lib/postgresql/data
    
volumes:
  slcm_db_data:
  