# Generated by Django 3.2.7 on 2022-10-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfercertificate',
            name='remaining_fees',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
