# Generated by Django 3.2.7 on 2022-10-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0002_auto_20221006_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_enrolled_type',
            field=models.CharField(choices=[('Studying', 'Studying'), ('Dropout', 'Dropout'), ('Passed Out', 'Passed Out')], default='School', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='current_status',
            field=models.CharField(blank=True, choices=[('Studying', 'Studying'), ('Dropout', 'Dropout'), ('Passed Out', 'Passed Out')], default='Studying', max_length=50),
        ),
    ]
