# Generated by Django 3.2.7 on 2022-10-07 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0005_auto_20221007_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='cast',
            new_name='caste',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mother_aaadhaar_id_number',
            new_name='mother_aadhaar_id_number',
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Number should only contains integers.', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Number should only contains integers.', regex='^[0-9]*$')]),
        ),
    ]
